### PR TITLE
Support ipywidgets 8

### PR DESCRIPTION
**Pull request by jtpio**
Since ipywidgets 8 final has now been released.

Still getting this error for now:

image

### CODE REVIEW

**Comment by jtpio** [comment]
CI passes but still the same issue as above.

**Comment by martinRenou** [comment]
Thanks for starting this! ipytree is still using the old Backbone `.extend`. It probably needs updating. I'm on it :)

**Comment by martinRenou** [comment]
Seems to be working fine once modernized a bit:

Screenshot from 2022-08-23 16-29-48

**Comment by martinRenou** [comment]
There is still an issue when it comes to removing nodes (hence some node duplication in the screenshot)

**Comment by jtpio** [comment]
nice thanks!

**Pull request merged**
